server:
  port: 8022
  session:
    timeout: 30

#  context-path: /girl
girl:
  cupSize: B
  age: 18
#content: "cupSize: ${cupSize}, age: ${age}"

system:
  base:
    path: http://127.0.0.1:8022/



spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;instanceName=MSSQLSERVER;DatabaseName=SPRING_BOOT_FIRST;sendStringParametersAsUnicode=false
    username: sa
    password: 123
